global_emotes = ["TriHard", "LUL", "LuL", "<3", "Kappa", "PogChamp", "PogU", "PagChomp",
                 "SMOrc", "cmonBruh", "4Head", ":D", ":)", "Kreygasm", "KappaPride", "WutFace",
                 "ResidentSleeper", "NotLikeThis", "forsenT", "BlessRNG", "MrDestructoid",
                 "HeyGuys", "BabyRage", "Keepo", "sum1g", "Jebaited", "SeemsGood", "SwiftRage",
                 "VoteYea", "VoteNay", "FailFish", "MingLee", "forsenE", "PJSalt",
                 "CoolStoryBob", "GivePLZ", "CoolCat", "ANELE", ":P", ";)", "EleGiggle",
                 "OpieOP", "SeriousSloth", "EarthDay", "FrankerZ", "OhMyDog", "DoritosChip",
                 "SSSsss", "BrokeBack", "NaM", "DuckerZ", "FireSpeed", "Clap", "haHAA",
                 "FeelsGoodMan", "gachiBASS", "FeelsBadMan", "D:", "forsenPls", "OMEGALUL",
                 "AYAYA", "monkaS", "monkaW", "monkaOMEGA", "monkaEyes", "pepeD", "SourPls",
                 "TriDance", "blobDance", "ricardoFlick", "gachiGASM", "PepePls", "pepeJAM",
                 "POGGERS", "pugPls", "gachiHYPER", "EZ", "EZY", "TriKool", "KKona",
                 "pepeDS", "PepeHands", "ppOverheat", "pepeLaugh", "PepeLaugh", "GachiPls", 
                 "PartyParrot", "PepeCheer", "KKool", "(ditto)", "headBang", "ZULUL",
                 "Pepega", "bigPls", "AlienPls", "AlienPls3", "FeelsAmazingMan", "Sadge", 
                 "ppHop", "FeelsBirthdayMan", "GuitarTime", "nyanPls", "TeaTime", "PepegaPls",
                 "AngelThump", "WAYTOODANK", "WAYTOOSMART", "sumSmash", "xqcSmash", "HYPERS",
                 "FishMoley", "billyReady", "forsenReady", "forsenSmug", "PedoBear",
                 "RareParrot", "peepoClap", "TriFi", "pepeMeltdown", "COGGERS", "bUrself",
                 "FeelsRainMan", "WideHardo", "pepeL", "LULW", "Pog", "KEKW", "Pepega", 
                 "WeirdChamp", "PepeHands", "YEP", "HandsUp", "4Weird", "Kapp", "5Head",
                 "widepeepoHappy", "WideHard", "forsenCD", "FeelsDankMan", "DICKS", "3Head",
                 "FeelsOkayMan", "HYPERBRUH", "FeelsWeirdMan", "HYPERBRUH", "FeelsWeirdManW",
                 "4HEad", "4Heed", "WideHarder", "OkayChamp", "KKonaW", "KKomrade",
                 "widepeepoSad", "PauseChamp", "FeelsStrongMan", "Man", "ZULUL", "ppL",
                 "PainsChamp", "Pepepains", "HYPERDANSGAME", "peepoHappy", "monkaHmm", "HYPERS",
                 "KKonaW", "4House", "peepoSad", "PogO", "MEGALUL", "RebeccaBlack", "CiGrip", 
                 "Zappa", "DansGame", "VisLaud", "KomodoHype", "SourPls", "PepePls", "FCreep",
                 "nymnCorn", "ViolinTime", "PianoTime", "Okayge", "Okayeg", "Pepege", "BasedGod"]
